import { Component, type ErrorInfo, type FormEvent, type ReactNode, useCallback, useEffect, useRef, useState } from "react";
import { appAdapter, type AppAdapter } from "./adapter";
import { defaultSettings, type AppSettings, type DashboardSnapshot, type ProviderUsage, type UsageWindow } from "./contracts";
import { formatDateTime, formatPercent, formatRelativeTime, isResetPending, moveProviderOrder, remainingTone, sourceLabel, statusLabel } from "./formatters";

type AppProps = { adapter?: AppAdapter };
type IconProps = { size?: number };

const ProviderMark = ({ provider, size = 20 }: IconProps & { provider: ProviderUsage }) => (
  <svg className="provider-mark" width={size} height={size} viewBox="0 0 24 24" aria-hidden="true">
    <circle cx="12" cy="12" r="10" className={`provider-mark__circle provider-mark__circle--${provider.id}`} />
    <path d={provider.id === "codex" ? "M7.3 8.1h5.2a3.1 3.1 0 0 1 0 6.2H7.3m4.1-3.1h5.3" : "M8 7.6h8M8 12h6.4M8 16.4h8"} className="provider-mark__path" />
  </svg>
);
const RefreshGlyph = ({ size = 16 }: IconProps) => <svg width={size} height={size} viewBox="0 0 24 24" aria-hidden="true"><path d="M19 8.3A7.5 7.5 0 1 0 19.2 15M19 4.5v4.8h-4.8" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round" /></svg>;
const SettingsGlyph = ({ size = 16 }: IconProps) => <svg width={size} height={size} viewBox="0 0 24 24" aria-hidden="true"><path d="m12 3 1.1 2.6 2.8.8 2.6-1.2 1.7 1.7-1.2 2.6.8 2.8L22.4 13v2l-2.6 1.1-.8 2.8 1.2 2.6-1.7 1.7-2.6-1.2-2.8.8L12 23l-2.1-2.2-2.8-.8-2.6 1.2-1.7-1.7L4 16.1 3.2 13 1 12V10l2.2-1.1L4 6.1 2.8 3.5 4.5 1.8l2.6 1.2L10 2.2 12 0" transform="scale(.9) translate(1.3 1.3)" fill="none" stroke="currentColor" strokeWidth="1.3" strokeLinejoin="round" /><circle cx="12" cy="12" r="3" fill="none" stroke="currentColor" strokeWidth="1.5" /></svg>;
const statusIcon = (status: ProviderUsage["status"]) => status === "fresh" ? "●" : status === "refreshing" ? "↻" : "!";

export const UsageRing = ({ value, provider, size = 44 }: { value: number | null; provider: ProviderUsage; size?: number }) => {
  const tone = remainingTone(value);
  const radius = 18;
  const circumference = 2 * Math.PI * radius;
  const dash = value === null ? 0 : Math.max(0, Math.min(100, value)) / 100 * circumference;
  return <span className={`usage-ring usage-ring--${tone}`} style={{ width: size, height: size }} aria-label={`残量 ${formatPercent(value)}`}><svg viewBox="0 0 44 44" aria-hidden="true"><circle className="usage-ring__track" cx="22" cy="22" r={radius} />{value !== null && <circle className="usage-ring__value" cx="22" cy="22" r={radius} strokeDasharray={`${dash} ${circumference - dash}`} />}</svg><span className="usage-ring__mark"><ProviderMark provider={provider} size={size > 38 ? 17 : 15} /></span></span>;
};
const LoadingState = ({ label = "使用量を読み込み中" }: { label?: string }) => <div className="loading-state" role="status"><span className="loading-state__bar" /><span>{label}…</span></div>;
const ErrorState = ({ message, onRetry }: { message: string; onRetry?: () => void }) => <div className="error-state" role="alert"><p>{message}</p>{onRetry && <button type="button" className="button button--ghost" onClick={onRetry}>再試行</button>}</div>;

const WindowBar = ({ window, now }: { window: UsageWindow; now: Date }) => {
  const tone = remainingTone(window.remainingPercent);
  const pending = isResetPending(window, now);
  return <div className={`window-row window-row--${tone}`}><div className="window-row__heading"><span>{window.label}</span><strong>{pending ? "リセット確認中" : `${formatPercent(window.remainingPercent)}残り`}</strong></div><div className="window-row__bar" aria-label={`${window.label} ${formatPercent(window.remainingPercent)}残り`}><span style={{ width: `${window.remainingPercent ?? 0}%` }} /></div><div className="window-row__meta"><span>使用済み {formatPercent(window.usedPercent)}</span><span>{pending ? "更新待ち" : `リセット ${formatDateTime(window.resetsAt, now)}`}</span></div></div>;
};
const ProviderDetail = ({ provider, now }: { provider: ProviderUsage; now: Date }) => <section className="widget-detail__content" aria-labelledby={`provider-detail-${provider.id}`}><div className="widget-detail__header"><div className="provider-heading"><ProviderMark provider={provider} size={25} /><div><h2 id={`provider-detail-${provider.id}`}>{provider.displayName}</h2><p>{provider.planName ?? "プラン情報なし"}</p></div></div><div className={`status status--${provider.status}`}><span aria-hidden="true">{statusIcon(provider.status)}</span>{statusLabel(provider.status)}</div></div><div className="provider-meta"><span>最終更新 {formatRelativeTime(provider.updatedAt, now)}</span><span>取得元 {sourceLabel(provider.source)}</span></div><div className="window-list">{provider.windows.length > 0 ? provider.windows.map((item) => <WindowBar key={`${provider.id}-${item.kind}`} window={item} now={now} />) : <p className="muted">利用できるウィンドウがありません。</p>}</div>{provider.lastError && <p className="inline-error">{provider.lastError}</p>}</section>;

const WidgetApp = ({ adapter }: { adapter: AppAdapter }) => {
  const [snapshot, setSnapshot] = useState<DashboardSnapshot | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [expandedProviderId, setExpandedProviderId] = useState<string | null>(null);
  const [pinned, setPinned] = useState(false);
  const [now, setNow] = useState(() => new Date());
  const closeTimer = useRef<number | undefined>(undefined);
  const openTimer = useRef<number | undefined>(undefined);
  const lastExpanded = useRef<boolean | undefined>(undefined);
  const notifyExpanded = useCallback((expanded: boolean) => { if (lastExpanded.current === expanded) return; lastExpanded.current = expanded; void adapter.setWidgetExpanded(expanded); }, [adapter]);
  const close = useCallback(() => { setExpandedProviderId(null); setPinned(false); notifyExpanded(false); }, [notifyExpanded]);
  const load = useCallback(async () => { try { setError(null); setSnapshot(await adapter.getDashboard()); } catch (caught) { setError(caught instanceof Error ? caught.message : "使用量を取得できませんでした。"); } }, [adapter]);
  useEffect(() => { void load(); const cleanup = adapter.onUsageUpdated(setSnapshot); const clock = window.setInterval(() => setNow(new Date()), 30_000); return () => { cleanup(); window.clearInterval(clock); window.clearTimeout(closeTimer.current); window.clearTimeout(openTimer.current); }; }, [adapter, load]);
  useEffect(() => { const handleWindowKeyDown = (event: KeyboardEvent) => { if (event.key === "Escape") close(); }; window.addEventListener("keydown", handleWindowKeyDown); return () => window.removeEventListener("keydown", handleWindowKeyDown); }, [close]);
  const providers = snapshot?.providers ?? [];
  const selected = providers.find((provider) => provider.id === expandedProviderId) ?? providers[0];
  const scheduleOpen = (providerId: string) => { window.clearTimeout(closeTimer.current); window.clearTimeout(openTimer.current); openTimer.current = window.setTimeout(() => { setExpandedProviderId(providerId); notifyExpanded(true); }, 150); };
  const scheduleClose = () => { window.clearTimeout(openTimer.current); if (!pinned) closeTimer.current = window.setTimeout(close, 300); };
  const selectProvider = (providerId: string, shouldPin = false) => { window.clearTimeout(openTimer.current); window.clearTimeout(closeTimer.current); setExpandedProviderId(providerId); if (shouldPin) setPinned((value) => !value); notifyExpanded(true); };
  const handleKeyDown = (event: React.KeyboardEvent<HTMLButtonElement>, providerId: string) => { if (event.key === "Escape") { event.preventDefault(); close(); } else if (event.key === "Enter" || event.key === " ") { event.preventDefault(); selectProvider(providerId, true); } else if (event.key === "ContextMenu" || (event.key === "F10" && event.shiftKey)) { event.preventDefault(); void adapter.openSettings(providerId); } };
  if (error) return <main className="widget-app"><ErrorState message={error} onRetry={() => void load()} /></main>;
  return <main className={`widget-app widget-app--${pinned ? "pinned" : "hover"}`} onMouseEnter={() => selected && scheduleOpen(selected.id)} onMouseLeave={scheduleClose}>{selected && expandedProviderId && <div className="widget-detail" onMouseEnter={() => window.clearTimeout(closeTimer.current)} onMouseLeave={scheduleClose}><ProviderDetail provider={selected} now={now} /></div>}<aside className="widget-rail" aria-label="使用量ウィジェット"><div className="widget-rail__top"><span className="widget-brand" aria-label="UsageDock">UD</span></div><div className="provider-stack">{snapshot ? providers.map((provider) => <button key={provider.id} type="button" className={`provider-button ${expandedProviderId === provider.id ? "provider-button--selected" : ""}`} aria-label={`${provider.displayName} ${formatPercent(provider.windows[0]?.remainingPercent ?? null)}残り`} aria-expanded={expandedProviderId === provider.id} onMouseEnter={() => scheduleOpen(provider.id)} onFocus={() => selectProvider(provider.id)} onClick={() => selectProvider(provider.id, true)} onContextMenu={(event) => { event.preventDefault(); void adapter.openSettings(provider.id); }} onKeyDown={(event) => handleKeyDown(event, provider.id)}><UsageRing value={provider.windows[0]?.remainingPercent ?? null} provider={provider} size={46} /><span className={`provider-button__percent provider-button__percent--${remainingTone(provider.windows[0]?.remainingPercent ?? null)}`}>{formatPercent(provider.windows[0]?.remainingPercent ?? null)}</span><span className={`provider-button__status provider-button__status--${provider.status}`} aria-label={statusLabel(provider.status)}>{statusIcon(provider.status)}</span></button>) : <LoadingState label="読込" />}</div><div className="widget-rail__bottom"><button type="button" className="icon-button" aria-label="使用量を更新" onClick={() => void adapter.refreshUsage()}><RefreshGlyph /></button><button type="button" className="icon-button" aria-label="設定を開く" onClick={() => void adapter.openSettings()}><SettingsGlyph /></button></div></aside></main>;
};

const navItems = [["general", "一般"], ["widget", "ウィジェット"], ["providers", "プロバイダー"], ["notifications", "通知"], ["advanced", "詳細設定"], ["about", "アプリ情報"]] as const;
type SettingsSection = typeof navItems[number][0];
const settingsWithDefaults = (value: AppSettings): AppSettings => ({ ...defaultSettings, ...value, notificationThresholds: { ...defaultSettings.notificationThresholds, ...value.notificationThresholds }, providerOrder: value.providerOrder?.length ? value.providerOrder : defaultSettings.providerOrder });

const SettingsApp = ({ adapter }: { adapter: AppAdapter }) => {
  const [settings, setSettings] = useState<AppSettings>(defaultSettings);
  const [section, setSection] = useState<SettingsSection>("general");
  const [status, setStatus] = useState<"idle" | "loading" | "saving" | "success" | "error">("loading");
  const [message, setMessage] = useState("");
  const [apiKey, setApiKey] = useState("");
  const [connecting, setConnecting] = useState(false);
  useEffect(() => { let active = true; void adapter.getSettings().then((value) => { if (active) { setSettings(settingsWithDefaults(value)); setStatus("idle"); } }).catch((caught) => { if (active) { setStatus("error"); setMessage(caught instanceof Error ? caught.message : "設定を読み込めませんでした。"); } }); return () => { active = false; }; }, [adapter]);
  const update = <K extends keyof AppSettings>(key: K, value: AppSettings[K]) => setSettings((current) => ({ ...current, [key]: value }));
  const save = async (event: FormEvent) => { event.preventDefault(); if (status === "saving") return; setStatus("saving"); try { await adapter.saveSettings(settings); setStatus("success"); setMessage("設定を保存しました。"); } catch (caught) { setStatus("error"); setMessage(caught instanceof Error ? caught.message : "設定を保存できませんでした。"); } };
  const connect = async () => { if (!apiKey || connecting) return; setConnecting(true); setMessage(""); try { await adapter.setOpencodeApiKey(apiKey); setApiKey(""); setMessage("OpenCode Goに接続しました。"); } catch (caught) { setMessage(caught instanceof Error ? caught.message : "接続できませんでした。"); } finally { setConnecting(false); } };
  const moveProvider = (index: number, direction: -1 | 1) => update("providerOrder", moveProviderOrder(settings.providerOrder, index, direction));
  return <main className="settings-app"><nav className="settings-nav" aria-label="設定カテゴリー"><div className="settings-nav__brand"><span className="widget-brand">UD</span><div><strong>UsageDock</strong><small>設定</small></div></div>{navItems.map(([id, label]) => <button type="button" key={id} className={section === id ? "settings-nav__item settings-nav__item--active" : "settings-nav__item"} aria-current={section === id ? "page" : undefined} onClick={() => setSection(id)}>{label}</button>)}</nav><form className="settings-content" onSubmit={(event) => void save(event)}><header className="settings-header"><div><p className="eyebrow">設定</p><h1>{navItems.find(([id]) => id === section)?.[1]}</h1></div><div className="settings-actions">{message && <p className={`save-message save-message--${status === "error" ? "error" : "success"}`} role={status === "error" ? "alert" : "status"}>{message}</p>}<button type="submit" className="button button--primary" disabled={status === "loading" || status === "saving"}>{status === "saving" ? "保存中…" : "変更を保存"}</button></div></header>{status === "loading" ? <LoadingState label="設定を読み込み中" /> : <SettingsSectionContent section={section} settings={settings} apiKey={apiKey} setApiKey={setApiKey} connecting={connecting} update={update} connect={() => void connect()} moveProvider={moveProvider} disconnect={() => void adapter.disconnectOpencode()} />}</form></main>;
};

type SettingsContentProps = { section: SettingsSection; settings: AppSettings; apiKey: string; setApiKey: (value: string) => void; connecting: boolean; update: <K extends keyof AppSettings>(key: K, value: AppSettings[K]) => void; connect: () => void; moveProvider: (index: number, direction: -1 | 1) => void; disconnect: () => void };
const SettingsSectionContent = ({ section, settings, apiKey, setApiKey, connecting, update, connect, moveProvider, disconnect }: SettingsContentProps) => {
  if (section === "general") return <section className="settings-section"><div className="section-intro"><h2>基本設定</h2><p>UsageDockの起動とデータ更新を調整します。</p></div><div className="settings-card settings-grid"><label className="field"><span>更新間隔</span><span className="field-inline"><input type="number" min="30" max="900" step="1" value={settings.refreshIntervalSeconds} onChange={(event) => update("refreshIntervalSeconds", Number(event.target.value))} /><small>秒（30〜900）</small></span></label><label className="toggle-field"><input type="checkbox" checked={settings.autoStart} onChange={(event) => update("autoStart", event.target.checked)} /><span><strong>Windows起動時に起動</strong><small>ログイン後に自動でUsageDockを起動します。</small></span></label><label className="toggle-field"><input type="checkbox" checked={settings.startInBackground} onChange={(event) => update("startInBackground", event.target.checked)} /><span><strong>バックグラウンドで開始</strong><small>起動時に設定画面を表示しません。</small></span></label></div></section>;
  if (section === "widget") return <section className="settings-section"><div className="section-intro"><h2>ウィジェット</h2><p>右端に固定されるウィジェットの見た目を調整します。</p></div><div className="settings-card settings-grid"><label className="field"><span>サイズ</span><select value={settings.widgetSize} onChange={(event) => update("widgetSize", event.target.value as AppSettings["widgetSize"])}><option value="s">S — コンパクト</option><option value="m">M — 標準</option><option value="l">L — 詳細</option></select></label><label className="field"><span>表示倍率</span><span className="field-inline"><input type="number" min="75" max="150" value={settings.scalePercent} onChange={(event) => update("scalePercent", Number(event.target.value))} /><small>%（75〜150）</small></span></label><label className="field"><span>不透明度</span><span className="field-inline"><input type="number" min="75" max="100" value={settings.opacityPercent} onChange={(event) => update("opacityPercent", Number(event.target.value))} /><small>%（75〜100）</small></span></label></div></section>;
  if (section === "providers") return <section className="settings-section"><div className="section-intro"><h2>プロバイダー</h2><p>表示するプロバイダーと順番を管理します。</p></div><div className="settings-card provider-settings"><label className="toggle-field"><input type="checkbox" checked={settings.codexEnabled} onChange={(event) => update("codexEnabled", event.target.checked)} /><span><strong>Codex</strong><small>App Serverから使用量を取得</small></span></label><label className="toggle-field"><input type="checkbox" checked={settings.openCodeGoEnabled} onChange={(event) => update("openCodeGoEnabled", event.target.checked)} /><span><strong>OpenCode Go</strong><small>APIから使用量を取得</small></span></label><div className="provider-order"><h3>表示順</h3>{settings.providerOrder.map((id, index) => <div className="provider-order__row" key={id}><span>{index + 1}</span><strong>{id === "codex" ? "Codex" : "OpenCode Go"}</strong><button type="button" className="button button--small" aria-label={`${id}を上へ`} disabled={index === 0} onClick={() => moveProvider(index, -1)}>上へ</button><button type="button" className="button button--small" aria-label={`${id}を下へ`} disabled={index === settings.providerOrder.length - 1} onClick={() => moveProvider(index, 1)}>下へ</button></div>)}</div><div className="provider-connection"><label className="field"><span>OpenCode APIキー</span><input type="password" autoComplete="off" value={apiKey} onChange={(event) => setApiKey(event.target.value)} placeholder="キーは表示・保存されません" /></label><div className="connection-actions"><button type="button" className="button button--secondary" disabled={!apiKey || connecting} onClick={connect}>{connecting ? "接続中…" : "接続"}</button><button type="button" className="button button--ghost" onClick={disconnect}>接続を解除</button></div></div></div></section>;
  if (section === "notifications") return <section className="settings-section"><div className="section-intro"><h2>通知</h2><p>残量が少なくなったときの通知条件です。</p></div><div className="settings-card settings-grid"><label className="toggle-field"><input type="checkbox" checked={settings.notificationThresholds.enabled} onChange={(event) => update("notificationThresholds", { ...settings.notificationThresholds, enabled: event.target.checked })} /><span><strong>残量通知を有効にする</strong><small>閾値を下回ったときに通知します。</small></span></label><label className="field"><span>注意の閾値</span><span className="field-inline"><input type="number" min="1" max="99" value={settings.notificationThresholds.warningPercent} onChange={(event) => update("notificationThresholds", { ...settings.notificationThresholds, warningPercent: Number(event.target.value) })} /><small>%以下</small></span></label><label className="field"><span>危険の閾値</span><span className="field-inline"><input type="number" min="0" max="98" value={settings.notificationThresholds.criticalPercent} onChange={(event) => update("notificationThresholds", { ...settings.notificationThresholds, criticalPercent: Number(event.target.value) })} /><small>%以下</small></span></label></div></section>;
  if (section === "advanced") return <section className="settings-section"><div className="section-intro"><h2>詳細設定</h2><p>互換性とローカル実行ファイルの設定です。</p></div><div className="settings-card settings-grid"><label className="field field--wide"><span>Codex実行ファイルのパス</span><input type="text" value={settings.codexPath ?? ""} onChange={(event) => update("codexPath", event.target.value || null)} placeholder="自動検出" /></label><label className="toggle-field"><input type="checkbox" checked={settings.forceCompatibilityMode} onChange={(event) => update("forceCompatibilityMode", event.target.checked)} /><span><strong>互換モードを強制</strong><small>古い環境での接続を優先します。</small></span></label></div></section>;
  const aboutProvider: ProviderUsage = { id: "codex", displayName: "UsageDock", planName: null, status: "fresh", source: "none", updatedAt: null, lastError: null, windows: [] };
  return <section className="settings-section"><div className="section-intro"><h2>アプリ情報</h2><p>UsageDockは使用量をすばやく確認するための常駐ウィジェットです。</p></div><div className="settings-card about-card"><span className="about-card__mark"><ProviderMark provider={aboutProvider} size={42} /></span><div><h3>UsageDock</h3><p>バージョン 0.1.0</p><p className="muted">データは設定したプロバイダーから取得されます。</p></div></div></section>;
};

class RootErrorBoundary extends Component<{ children: ReactNode }, { error: Error | null }> { state: { error: Error | null } = { error: null }; static getDerivedStateFromError(error: Error) { return { error }; } componentDidCatch(error: Error, info: ErrorInfo) { console.error("UsageDock UI error", error, info); } render() { return this.state.error ? <main className="root-error" role="alert"><h1>画面を表示できません</h1><p>{this.state.error.message}</p><button type="button" className="button button--primary" onClick={() => window.location.reload()}>再読み込み</button></main> : this.props.children; } }
export function App({ adapter = appAdapter }: AppProps) { const [label, setLabel] = useState<"widget" | "settings" | null>(null); useEffect(() => { setLabel(adapter.getWindowLabel()); }, [adapter]); if (!label) return <main className="bootstrap"><LoadingState /></main>; return <RootErrorBoundary>{label === "settings" ? <SettingsApp adapter={adapter} /> : <WidgetApp adapter={adapter} />}</RootErrorBoundary>; }
export { SettingsApp, WidgetApp };
